pub mod targets;

use crate::detector::Detection;
use anyhow::Result;
use std::path::Path;

const DEJAVU_SECTION_START: &str = "<!-- dejavu:start -->";
const DEJAVU_SECTION_END: &str = "<!-- dejavu:end -->";

pub fn format_rule(rule_id: &str, detection: &Detection) -> String {
    let sessions_str = detection
        .evidence
        .sessions
        .iter()
        .map(|s| &s[..s.len().min(7)])
        .collect::<Vec<_>>()
        .join(", ");

    let now = chrono::Utc::now().format("%Y-%m-%d").to_string();

    format!(
        "<!-- dejavu:rule id={rule_id} -->\n\
         <!-- dejavu:evidence sessions=[{sessions_str}] confidence={confidence:.2} fires=0 -->\n\
         <!-- dejavu:created={now} last-fired=never -->\n\
         \n\
         - {rule_text}\n\
         \n",
        rule_id = rule_id,
        sessions_str = sessions_str,
        confidence = detection.confidence,
        now = now,
        rule_text = detection.suggested_rule,
    )
}

pub fn patch_claude_md(project_path: &Path, rules: &[(String, Detection)]) -> Result<String> {
    let claude_md_path = project_path.join("CLAUDE.md");

    let existing_content = if claude_md_path.exists() {
        std::fs::read_to_string(&claude_md_path)?
    } else {
        String::new()
    };

    let (before_section, _existing_rules, after_section) = split_dejavu_section(&existing_content);

    let mut new_rules_section = String::new();
    new_rules_section.push_str(DEJAVU_SECTION_START);
    new_rules_section.push('\n');
    new_rules_section.push_str("## Learned Rules (auto-generated by dejavu)\n\n");

    for (id, detection) in rules {
        new_rules_section.push_str(&format_rule(id, detection));
    }

    new_rules_section.push_str(DEJAVU_SECTION_END);
    new_rules_section.push('\n');

    let result = format!("{}{}{}", before_section, new_rules_section, after_section);
    Ok(result)
}

pub fn write_claude_md(project_path: &Path, content: &str) -> Result<()> {
    let claude_md_path = project_path.join("CLAUDE.md");
    std::fs::write(claude_md_path, content)?;
    Ok(())
}

fn split_dejavu_section(content: &str) -> (&str, &str, &str) {
    if let Some(start_pos) = content.find(DEJAVU_SECTION_START) {
        if let Some(end_pos) = content.find(DEJAVU_SECTION_END) {
            let end_pos = end_pos + DEJAVU_SECTION_END.len();
            // Skip trailing newline if present
            let end_pos = if content[end_pos..].starts_with('\n') {
                end_pos + 1
            } else {
                end_pos
            };
            return (
                &content[..start_pos],
                &content[start_pos..end_pos],
                &content[end_pos..],
            );
        }
    }
    (content, "", "")
}
