pub mod targets;

use crate::detector::Detection;
use anyhow::Result;
use std::path::Path;

const DEJAVU_SECTION_START: &str = "<!-- dejavu:start -->";
const DEJAVU_SECTION_END: &str = "<!-- dejavu:end -->";

pub fn format_rule(rule_id: &str, detection: &Detection) -> String {
    let sessions_str = detection
        .evidence
        .sessions
        .iter()
        .map(|s| &s[..s.len().min(7)])
        .collect::<Vec<_>>()
        .join(", ");

    let now = chrono::Utc::now().format("%Y-%m-%d").to_string();

    format!(
        "<!-- dejavu:rule id={rule_id} -->\n\
         <!-- dejavu:evidence sessions=[{sessions_str}] confidence={confidence:.2} fires=0 -->\n\
         <!-- dejavu:created={now} last-fired=never -->\n\
         \n\
         - {rule_text}\n\
         \n",
        rule_id = rule_id,
        sessions_str = sessions_str,
        confidence = detection.confidence,
        now = now,
        rule_text = detection.suggested_rule,
    )
}

pub fn format_rules_plain(rules: &[(String, Detection)]) -> String {
    let mut out = String::new();
    for (_id, detection) in rules {
        out.push_str(&format!("- {}\n", detection.suggested_rule));
    }
    out
}

pub fn patch_claude_md(project_path: &Path, rules: &[(String, Detection)]) -> Result<String> {
    let claude_md_path = project_path.join("CLAUDE.md");
    patch_target(&claude_md_path, rules)
}

/// Patch any target file with dejavu rules section.
pub fn patch_target(target_path: &Path, rules: &[(String, Detection)]) -> Result<String> {
    let existing_content = if target_path.exists() {
        std::fs::read_to_string(target_path)?
    } else {
        String::new()
    };

    let (before_section, _existing_rules, after_section) = split_dejavu_section(&existing_content);

    let mut new_rules_section = String::new();
    new_rules_section.push_str(DEJAVU_SECTION_START);
    new_rules_section.push('\n');
    new_rules_section.push_str("## Learned Rules (auto-generated by dejavu)\n\n");

    for (id, detection) in rules {
        new_rules_section.push_str(&format_rule(id, detection));
    }

    new_rules_section.push_str(DEJAVU_SECTION_END);
    new_rules_section.push('\n');

    let result = format!("{}{}{}", before_section, new_rules_section, after_section);
    Ok(result)
}

pub fn write_claude_md(project_path: &Path, content: &str) -> Result<()> {
    let claude_md_path = project_path.join("CLAUDE.md");
    std::fs::write(claude_md_path, content)?;
    Ok(())
}

/// Write rules to the appropriate target based on scope.
pub fn write_to_target(
    project_path: &Path,
    rules: &[(String, Detection)],
    scope: &targets::RuleScope,
) -> Result<()> {
    let all_targets = targets::discover_targets(project_path);

    let target = targets::best_target_for_scope(&all_targets, scope.clone());

    let Some(target) = target else {
        // Fallback to CLAUDE.md
        let content = patch_claude_md(project_path, rules)?;
        write_claude_md(project_path, &content)?;
        return Ok(());
    };

    // Ensure parent directory exists
    if let Some(parent) = target.path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let content = patch_target(&target.path, rules)?;
    std::fs::write(&target.path, content)?;

    Ok(())
}

/// Write global rules to ~/.claude/CLAUDE.md
pub fn write_global_rules(rules: &[(String, Detection)]) -> Result<()> {
    let global_path = dirs::home_dir()
        .ok_or_else(|| anyhow::anyhow!("no home dir"))?
        .join(".claude")
        .join("CLAUDE.md");

    if let Some(parent) = global_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let content = patch_target(&global_path, rules)?;
    std::fs::write(&global_path, content)?;

    Ok(())
}

fn split_dejavu_section(content: &str) -> (&str, &str, &str) {
    if let Some(start_pos) = content.find(DEJAVU_SECTION_START)
        && let Some(end_pos) = content.find(DEJAVU_SECTION_END)
    {
        let end_pos = end_pos + DEJAVU_SECTION_END.len();
        let end_pos = if content[end_pos..].starts_with('\n') {
            end_pos + 1
        } else {
            end_pos
        };
        return (
            &content[..start_pos],
            &content[start_pos..end_pos],
            &content[end_pos..],
        );
    }
    (content, "", "")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::detector::{Detection, DetectorType, Evidence};

    fn make_detection(rule_text: &str) -> Detection {
        Detection {
            detector_type: DetectorType::UserCorrection,
            evidence: Evidence {
                sessions: vec!["session1".to_string(), "session2".to_string()],
                file_paths: vec![],
                occurrences: 2,
                details: serde_json::json!({}),
            },
            confidence: 0.85,
            suggested_rule: rule_text.to_string(),
        }
    }

    #[test]
    fn patch_target_inserts_into_empty_content() {
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), "").unwrap();

        let rules = vec![("rule_001".to_string(), make_detection("Always use pnpm"))];
        let result = patch_target(tmp.path(), &rules).unwrap();

        assert!(result.contains(DEJAVU_SECTION_START));
        assert!(result.contains(DEJAVU_SECTION_END));
        assert!(result.contains("Always use pnpm"));
        assert!(result.contains("Learned Rules"));
    }

    #[test]
    fn patch_target_replaces_existing_section() {
        let existing = format!(
            "# My Project\n\nSome docs.\n\n{}\n## Learned Rules (auto-generated by dejavu)\n\nOld rule here.\n{}\n\n## Other section\n",
            DEJAVU_SECTION_START, DEJAVU_SECTION_END,
        );

        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &existing).unwrap();

        let rules = vec![("rule_002".to_string(), make_detection("New rule text"))];
        let result = patch_target(tmp.path(), &rules).unwrap();

        assert!(result.contains("New rule text"));
        assert!(!result.contains("Old rule here"));
        assert!(result.contains("# My Project"));
        assert!(result.contains("## Other section"));
        // Should have exactly one start and one end marker
        assert_eq!(
            result.matches(DEJAVU_SECTION_START).count(),
            1,
            "should have exactly one start marker"
        );
        assert_eq!(
            result.matches(DEJAVU_SECTION_END).count(),
            1,
            "should have exactly one end marker"
        );
    }

    #[test]
    fn patch_target_preserves_content_before_and_after() {
        let existing = format!(
            "Before content\n{}\nold rules\n{}\nAfter content\n",
            DEJAVU_SECTION_START, DEJAVU_SECTION_END,
        );

        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &existing).unwrap();

        let rules = vec![("rule_003".to_string(), make_detection("Updated rule"))];
        let result = patch_target(tmp.path(), &rules).unwrap();

        assert!(result.starts_with("Before content\n"));
        assert!(result.contains("After content"));
        assert!(result.contains("Updated rule"));
    }

    #[test]
    fn split_dejavu_section_no_section() {
        let content = "# Hello\n\nSome content.";
        let (before, section, after) = split_dejavu_section(content);
        assert_eq!(before, content);
        assert_eq!(section, "");
        assert_eq!(after, "");
    }

    #[test]
    fn split_dejavu_section_with_section() {
        let content = format!(
            "Before\n{}\nRules here\n{}\nAfter\n",
            DEJAVU_SECTION_START, DEJAVU_SECTION_END,
        );
        let (before, section, after) = split_dejavu_section(&content);
        assert_eq!(before, "Before\n");
        assert!(section.contains(DEJAVU_SECTION_START));
        assert!(section.contains(DEJAVU_SECTION_END));
        assert_eq!(after, "After\n");
    }

    #[test]
    fn format_rule_contains_key_elements() {
        let detection = make_detection("Use pnpm not npm");
        let rule_text = format_rule("rule_test", &detection);

        assert!(rule_text.contains("rule_test"));
        assert!(rule_text.contains("Use pnpm not npm"));
        assert!(rule_text.contains("0.85"));
        // session IDs are truncated to 7 chars
        assert!(rule_text.contains("session"));
    }

    #[test]
    fn format_rules_plain_lists_all_rules() {
        let rules = vec![
            ("r1".to_string(), make_detection("Rule one")),
            ("r2".to_string(), make_detection("Rule two")),
        ];
        let plain = format_rules_plain(&rules);
        assert!(plain.contains("- Rule one"));
        assert!(plain.contains("- Rule two"));
    }
}
