pub mod targets;

use crate::detector::Detection;
use anyhow::Result;
use std::path::Path;

const DEJAVU_SECTION_START: &str = "<!-- dejavu:start -->";
const DEJAVU_SECTION_END: &str = "<!-- dejavu:end -->";

pub fn format_rule(rule_id: &str, detection: &Detection) -> String {
    let sessions_str = detection
        .evidence
        .sessions
        .iter()
        .map(|s| &s[..s.len().min(7)])
        .collect::<Vec<_>>()
        .join(", ");

    let now = chrono::Utc::now().format("%Y-%m-%d").to_string();

    format!(
        "<!-- dejavu:rule id={rule_id} -->\n\
         <!-- dejavu:evidence sessions=[{sessions_str}] confidence={confidence:.2} fires=0 -->\n\
         <!-- dejavu:created={now} last-fired=never -->\n\
         \n\
         - {rule_text}\n\
         \n",
        rule_id = rule_id,
        sessions_str = sessions_str,
        confidence = detection.confidence,
        now = now,
        rule_text = detection.suggested_rule,
    )
}

pub fn format_rules_plain(rules: &[(String, Detection)]) -> String {
    let mut out = String::new();
    for (_id, detection) in rules {
        out.push_str(&format!("- {}\n", detection.suggested_rule));
    }
    out
}

pub fn patch_claude_md(project_path: &Path, rules: &[(String, Detection)]) -> Result<String> {
    let claude_md_path = project_path.join("CLAUDE.md");
    patch_target(&claude_md_path, rules)
}

/// Patch any target file with dejavu rules section.
pub fn patch_target(target_path: &Path, rules: &[(String, Detection)]) -> Result<String> {
    let existing_content = if target_path.exists() {
        std::fs::read_to_string(target_path)?
    } else {
        String::new()
    };

    let (before_section, _existing_rules, after_section) = split_dejavu_section(&existing_content);

    let mut new_rules_section = String::new();
    new_rules_section.push_str(DEJAVU_SECTION_START);
    new_rules_section.push('\n');
    new_rules_section.push_str("## Learned Rules (auto-generated by dejavu)\n\n");

    for (id, detection) in rules {
        new_rules_section.push_str(&format_rule(id, detection));
    }

    new_rules_section.push_str(DEJAVU_SECTION_END);
    new_rules_section.push('\n');

    let result = format!("{}{}{}", before_section, new_rules_section, after_section);
    Ok(result)
}

pub fn write_claude_md(project_path: &Path, content: &str) -> Result<()> {
    let claude_md_path = project_path.join("CLAUDE.md");
    std::fs::write(claude_md_path, content)?;
    Ok(())
}

/// Write rules to the appropriate target based on scope.
pub fn write_to_target(
    project_path: &Path,
    rules: &[(String, Detection)],
    scope: &targets::RuleScope,
) -> Result<()> {
    let all_targets = targets::discover_targets(project_path);

    let target = targets::best_target_for_scope(&all_targets, scope.clone());

    let Some(target) = target else {
        // Fallback to CLAUDE.md
        let content = patch_claude_md(project_path, rules)?;
        write_claude_md(project_path, &content)?;
        return Ok(());
    };

    // Ensure parent directory exists
    if let Some(parent) = target.path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let content = patch_target(&target.path, rules)?;
    std::fs::write(&target.path, content)?;

    Ok(())
}

/// Write global rules to ~/.claude/CLAUDE.md
pub fn write_global_rules(rules: &[(String, Detection)]) -> Result<()> {
    let global_path = dirs::home_dir()
        .ok_or_else(|| anyhow::anyhow!("no home dir"))?
        .join(".claude")
        .join("CLAUDE.md");

    if let Some(parent) = global_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let content = patch_target(&global_path, rules)?;
    std::fs::write(&global_path, content)?;

    Ok(())
}

fn split_dejavu_section(content: &str) -> (&str, &str, &str) {
    if let Some(start_pos) = content.find(DEJAVU_SECTION_START)
        && let Some(end_pos) = content.find(DEJAVU_SECTION_END)
    {
        let end_pos = end_pos + DEJAVU_SECTION_END.len();
        let end_pos = if content[end_pos..].starts_with('\n') {
            end_pos + 1
        } else {
            end_pos
        };
        return (
            &content[..start_pos],
            &content[start_pos..end_pos],
            &content[end_pos..],
        );
    }
    (content, "", "")
}
